apiVersion: v1
kind: Service
metadata:
  name: {{ include "desc-webapp.fullname" . }}-records-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "desc-webapp.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "desc-webapp.name" . }}-records-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "desc-webapp.name" . }}-records-svc
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.recordsService.port }}
      targetPort: http
